schema_version: 1

context:
  name: rocm-cmake
  version: "7.0.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/ROCm/rocm-cmake/archive/refs/tags/rocm-${{ version }}.tar.gz
  sha256: 79c40408be17f7c73105e281154267fcc6851e1db8b6be01a411ef1d8050bc71

build:
  number: 1
  skip: not linux

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - cmake
    - make
  host:
    - rocm-core 7.0.2.*
  run:

tests:
  - script:
      - test -f $PREFIX/share/rocm/cmake/ROCMConfig.cmake

about:
  license: MIT
  license_file: LICENSE
  summary: Rocm cmake modules
  homepage: https://github.com/ROCm/rocm-cmake

extra:
  recipe-maintainers:
    - isuruf
    - conda-forge/rocm-core
